name: chain_cli
description: Used to manage and generate seed pharse 
version: 1.0.0
repository: https://github.com/venbrinoDev/chain_cli.git
homepage: https://github.com/venbrinoDev/chain_cli
issue_tracker: https://github.com/venbrinoDev/chain_cli/issues

environment:
  sdk: ^3.2.6


dependencies:
  bip39: ^1.0.6
  dcli: ^3.3.6
  args: ^2.4.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

executables: 
  chain_cli: chain_install